name: mnist
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.10
  - keras=2.3.1
  - pandas=1.0.3
  - numpy=1.18.4
  - scikit-learn=0.20.0
  - cloudpickle=1.4.1
  - pydot=1.4.1
  - pillow=7.1.2
  - scipy=1.4.1
  - imageio=2.8.0
  - flask=1.1.2
  - tensorflow=1.13.2
  - jupyterlab=2.1.2
  - matplotlib=3.2.1
  - flask-bootstrap=3.3.7.1

